### ISSUE TITLE
Selenium Grid support.

### ISSUE THREAD

**Issue by jayeshd7** [WasiqB/coteafs-selenium#83]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by WasiqB** [comment]
@jayeshd7 , #13 is already open for cloud support. We can make this ticket for specific to selenium grid support.

**Comment by WasiqB** [comment]
@jayeshd7 , can you check if Selenium grid is working with latest changes in develop branch?

**Comment by jayeshd7** [comment]
I will check and let you know.

**Comment by jayeshd7** [comment]
user_id: 
  password: e2eTest123
  protocol: HTTPS
  url: hub-cloud.browserstack.com
  source: BROWSERSTACK

this url is showing insure connection
and I am not getting what is below parameter 
name: Bstack-[Java] Sample Test

i am not able to see where we are using this with capabilities object.

**Comment by WasiqB** [comment]
You can modify the setting for Selenium Grid as follows:

```yaml
browser: CHROME
url: http://demo.guru99.com/V4/
remote:
  url: localhost
  port: 4444
  source: GRID
  capabilities:  # Grid specific capabilities. Key - Value pair.
    browser: Chrome
    browser_version: 75.0
    os: Windows
    os_version: 10
    resolution: 1024x768
params:
  user: mngr26593
  password: abc@123
playback:
  screen_state: NORMAL
  highlight: true
  screen_resolution:
    width: 1280
    height: 768
  delays:
    implicit: 60
    explicit: 60
    before_key_press: 0
    after_key_press: 0
    before_mouse_move: 0
    after_mouse_move: 0
    before_click: 0
    after_click: 0
    page_load: 60
    script_load: 60
    highlight: 500
  screenshot:
    path: ~/screenshots
    prefix: SCR
    extension: jpeg
    capture_on_error: false
```

I think this should work. My implementation is generic.
